/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayReturnRouteImport } from './routes/pay.return'
import { Route as PayLinkIdRouteImport } from './routes/pay.$linkId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPhoneRouteImport } from './routes/_authenticated/phone'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiVoiceTwimlRouteImport } from './routes/api/voice/twiml'
import { Route as ApiVoiceIncomingRouteImport } from './routes/api/voice/incoming'
import { Route as AuthenticatedOnboardingPhoneRouteImport } from './routes/_authenticated/onboarding/phone'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin/payouts'
import { Route as AuthenticatedAdminKycRouteImport } from './routes/_authenticated/admin/kyc'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsPhoneWebhookRouteImport } from './routes/api/public/payments/phone-webhook'
import { Route as ApiPublicPaymentsElgiopayWebhookRouteImport } from './routes/api/public/payments/elgiopay-webhook'
import { Route as ApiPublicHooksSubscriptionRemindersRouteImport } from './routes/api/public/hooks/subscription-reminders'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayReturnRoute = PayReturnRouteImport.update({
  id: '/pay/return',
  path: '/pay/return',
  getParentRoute: () => rootRouteImport,
} as any)
const PayLinkIdRoute = PayLinkIdRouteImport.update({
  id: '/pay/$linkId',
  path: '/pay/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhoneRoute = AuthenticatedPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTwimlRoute = ApiVoiceTwimlRouteImport.update({
  id: '/api/voice/twiml',
  path: '/api/voice/twiml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceIncomingRoute = ApiVoiceIncomingRouteImport.update({
  id: '/api/voice/incoming',
  path: '/api/voice/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingPhoneRoute =
  AuthenticatedOnboardingPhoneRouteImport.update({
    id: '/onboarding/phone',
    path: '/onboarding/phone',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/admin/payouts',
    path: '/admin/payouts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKycRoute = AuthenticatedAdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsPhoneWebhookRoute =
  ApiPublicPaymentsPhoneWebhookRouteImport.update({
    id: '/api/public/payments/phone-webhook',
    path: '/api/public/payments/phone-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsElgiopayWebhookRoute =
  ApiPublicPaymentsElgiopayWebhookRouteImport.update({
    id: '/api/public/payments/elgiopay-webhook',
    path: '/api/public/payments/elgiopay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSubscriptionRemindersRoute =
  ApiPublicHooksSubscriptionRemindersRouteImport.update({
    id: '/api/public/hooks/subscription-reminders',
    path: '/api/public/hooks/subscription-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/phone': typeof AuthenticatedPhoneRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/pay/$linkId': typeof PayLinkIdRoute
  '/pay/return': typeof PayReturnRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/onboarding/phone': typeof AuthenticatedOnboardingPhoneRoute
  '/api/voice/incoming': typeof ApiVoiceIncomingRoute
  '/api/voice/twiml': typeof ApiVoiceTwimlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/subscription-reminders': typeof ApiPublicHooksSubscriptionRemindersRoute
  '/api/public/payments/elgiopay-webhook': typeof ApiPublicPaymentsElgiopayWebhookRoute
  '/api/public/payments/phone-webhook': typeof ApiPublicPaymentsPhoneWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/phone': typeof AuthenticatedPhoneRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/pay/$linkId': typeof PayLinkIdRoute
  '/pay/return': typeof PayReturnRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/onboarding/phone': typeof AuthenticatedOnboardingPhoneRoute
  '/api/voice/incoming': typeof ApiVoiceIncomingRoute
  '/api/voice/twiml': typeof ApiVoiceTwimlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/subscription-reminders': typeof ApiPublicHooksSubscriptionRemindersRoute
  '/api/public/payments/elgiopay-webhook': typeof ApiPublicPaymentsElgiopayWebhookRoute
  '/api/public/payments/phone-webhook': typeof ApiPublicPaymentsPhoneWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/phone': typeof AuthenticatedPhoneRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/pay/$linkId': typeof PayLinkIdRoute
  '/pay/return': typeof PayReturnRoute
  '/_authenticated/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/onboarding/phone': typeof AuthenticatedOnboardingPhoneRoute
  '/api/voice/incoming': typeof ApiVoiceIncomingRoute
  '/api/voice/twiml': typeof ApiVoiceTwimlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/subscription-reminders': typeof ApiPublicHooksSubscriptionRemindersRoute
  '/api/public/payments/elgiopay-webhook': typeof ApiPublicPaymentsElgiopayWebhookRoute
  '/api/public/payments/phone-webhook': typeof ApiPublicPaymentsPhoneWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/unsubscribe'
    | '/verify-email'
    | '/billing'
    | '/crm'
    | '/dashboard'
    | '/kyc'
    | '/payments'
    | '/phone'
    | '/settings'
    | '/email/unsubscribe'
    | '/pay/$linkId'
    | '/pay/return'
    | '/admin/kyc'
    | '/admin/payouts'
    | '/onboarding/phone'
    | '/api/voice/incoming'
    | '/api/voice/twiml'
    | '/lovable/email/suppression'
    | '/api/public/hooks/subscription-reminders'
    | '/api/public/payments/elgiopay-webhook'
    | '/api/public/payments/phone-webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/unsubscribe'
    | '/verify-email'
    | '/billing'
    | '/crm'
    | '/dashboard'
    | '/kyc'
    | '/payments'
    | '/phone'
    | '/settings'
    | '/email/unsubscribe'
    | '/pay/$linkId'
    | '/pay/return'
    | '/admin/kyc'
    | '/admin/payouts'
    | '/onboarding/phone'
    | '/api/voice/incoming'
    | '/api/voice/twiml'
    | '/lovable/email/suppression'
    | '/api/public/hooks/subscription-reminders'
    | '/api/public/payments/elgiopay-webhook'
    | '/api/public/payments/phone-webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/unsubscribe'
    | '/verify-email'
    | '/_authenticated/billing'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/kyc'
    | '/_authenticated/payments'
    | '/_authenticated/phone'
    | '/_authenticated/settings'
    | '/email/unsubscribe'
    | '/pay/$linkId'
    | '/pay/return'
    | '/_authenticated/admin/kyc'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/onboarding/phone'
    | '/api/voice/incoming'
    | '/api/voice/twiml'
    | '/lovable/email/suppression'
    | '/api/public/hooks/subscription-reminders'
    | '/api/public/payments/elgiopay-webhook'
    | '/api/public/payments/phone-webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PayLinkIdRoute: typeof PayLinkIdRoute
  PayReturnRoute: typeof PayReturnRoute
  ApiVoiceIncomingRoute: typeof ApiVoiceIncomingRoute
  ApiVoiceTwimlRoute: typeof ApiVoiceTwimlRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksSubscriptionRemindersRoute: typeof ApiPublicHooksSubscriptionRemindersRoute
  ApiPublicPaymentsElgiopayWebhookRoute: typeof ApiPublicPaymentsElgiopayWebhookRoute
  ApiPublicPaymentsPhoneWebhookRoute: typeof ApiPublicPaymentsPhoneWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/return': {
      id: '/pay/return'
      path: '/pay/return'
      fullPath: '/pay/return'
      preLoaderRoute: typeof PayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$linkId': {
      id: '/pay/$linkId'
      path: '/pay/$linkId'
      fullPath: '/pay/$linkId'
      preLoaderRoute: typeof PayLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/phone': {
      id: '/_authenticated/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof AuthenticatedPhoneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/twiml': {
      id: '/api/voice/twiml'
      path: '/api/voice/twiml'
      fullPath: '/api/voice/twiml'
      preLoaderRoute: typeof ApiVoiceTwimlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/incoming': {
      id: '/api/voice/incoming'
      path: '/api/voice/incoming'
      fullPath: '/api/voice/incoming'
      preLoaderRoute: typeof ApiVoiceIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding/phone': {
      id: '/_authenticated/onboarding/phone'
      path: '/onboarding/phone'
      fullPath: '/onboarding/phone'
      preLoaderRoute: typeof AuthenticatedOnboardingPhoneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/kyc': {
      id: '/_authenticated/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AuthenticatedAdminKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/phone-webhook': {
      id: '/api/public/payments/phone-webhook'
      path: '/api/public/payments/phone-webhook'
      fullPath: '/api/public/payments/phone-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsPhoneWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/elgiopay-webhook': {
      id: '/api/public/payments/elgiopay-webhook'
      path: '/api/public/payments/elgiopay-webhook'
      fullPath: '/api/public/payments/elgiopay-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsElgiopayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/subscription-reminders': {
      id: '/api/public/hooks/subscription-reminders'
      path: '/api/public/hooks/subscription-reminders'
      fullPath: '/api/public/hooks/subscription-reminders'
      preLoaderRoute: typeof ApiPublicHooksSubscriptionRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPhoneRoute: typeof AuthenticatedPhoneRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminKycRoute: typeof AuthenticatedAdminKycRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedOnboardingPhoneRoute: typeof AuthenticatedOnboardingPhoneRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPhoneRoute: AuthenticatedPhoneRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminKycRoute: AuthenticatedAdminKycRoute,
  AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
  AuthenticatedOnboardingPhoneRoute: AuthenticatedOnboardingPhoneRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PayLinkIdRoute: PayLinkIdRoute,
  PayReturnRoute: PayReturnRoute,
  ApiVoiceIncomingRoute: ApiVoiceIncomingRoute,
  ApiVoiceTwimlRoute: ApiVoiceTwimlRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksSubscriptionRemindersRoute:
    ApiPublicHooksSubscriptionRemindersRoute,
  ApiPublicPaymentsElgiopayWebhookRoute: ApiPublicPaymentsElgiopayWebhookRoute,
  ApiPublicPaymentsPhoneWebhookRoute: ApiPublicPaymentsPhoneWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
